import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <header className="navbar glass-card">
          <div className="navbar-container">
            <Link href="/" className="nav-logo">
              <span className="logo-icon">&lt;/&gt;</span>
              <span className="logo-text">Tom<span className="gradient-text">.dev</span></span>
            </Link>
            <nav className="nav-links">
              <Link href="/" className="nav-link">Dashboard</Link>
              <Link href="/cv" className="nav-link">My CV</Link>
            </nav>
          </div>
        </header>
        <div style={{ flex: 1 }}>{children}</div>
      </body>
    </html>
  );
}
